### ISSUE TITLE
Embeded Jaeger - Links to code not always linkable

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#1493] opened 2023-12-17 14:33 UTC
looks like need to have some scroll or something else so that link would be available for link

the relevant button is:

![image](https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/37628831-ce1e-4d0e-88d1-9ccf3f17dbad)

attaching screen video which describes the issue (see around 0:20):

https://github.com/digma-ai/digma-intellij-plugin/assets/104715391/10bd1ec4-cb0c-4bf8-a03d-8b4f86f19f5f

**Comment by kshmidt-digma** [comment] 2024-02-02 20:13
Closed as duplicate of https://github.com/digma-ai/jaeger-ui/issues/43

**Closed by kshmidt-digma** 2024-02-02 20:13 UTC
Labels: bug, embedded.jaeger
