### ISSUE TITLE
Digma plugin exception

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#480] opened 2023-04-02 21:10 UTC
Happened when I clicked on an endpoint in the Recent Activity, that also changed the environment in the Digma side panel
Does not reproduce consistently

Details: Current thread: Thread[ApplicationImpl pooled thread 85,4,main] 129154253
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 717912862

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:988)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:767)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:390)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:167)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:103)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:91)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:34)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.findPsiMethodByMethodCodeObjectId(JavaLanguageService.java:343)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.lambda$findWorkspaceUrisForMethodCodeObjectIds$3(JavaLanguageService.java:322)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.findWorkspaceUrisForMethodCodeObjectIds(JavaLanguageService.java:320)
	at org.digma.intellij.plugin.insights.view.WorkspaceUrisHelper.findWorkspaceUrisMethodCodeObjectIds(WorkspaceUrisHelper.java:37)
	at org.digma.intellij.plugin.insights.view.WorkspaceUrisHelper.findWorkspaceUrisForMethodCodeObjectIds(WorkspaceUrisHelper.java:28)
	at org.digma.intellij.plugin.insights.view.GroupListViewItemBuilder.build(GroupListViewItemBuilder.java:63)
	at org.digma.intellij.plugin.insights.view.InsightsViewBuilder.lambda$build$0(InsightsViewBuilder.java:49)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.insights.view.InsightsViewBuilder.build(InsightsViewBuilder.java:47)
	at org.digma.intellij.plugin.insights.InsightsProvider.getInsightsListContainer(InsightsProvider.java:58)
	at org.digma.intellij.plugin.insights.InsightsProvider.getCachedInsights(InsightsProvider.java:44)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModel(InsightsViewService.kt:60)
	at org.digma.intellij.plugin.service.EditorInteractionService.contextChangedImpl(EditorInteractionService.java:129)
	at org.digma.intellij.plugin.service.EditorInteractionService.lambda$contextChanged$0(EditorInteractionService.java:76)
	at org.digma.intellij.plugin.common.Backgroundable$1.run(Backgroundable.java:29)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by arik-dig** [comment] 2023-04-03 05:15
duplicate of #449

**Comment by arik-dig** [comment] 2023-04-03 13:53
closing since duplicate

**Closed by arik-dig** 2023-04-03 13:53 UTC
Labels: bug
