### ISSUE TITLE
Flickering in empty state panel

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1255] opened 2023-09-06 16:23 UTC
See attached animated gif
 [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbjV5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--c93fb65787229dd81da23e0a9880248ea15bc6a3/idea64_x8ayaxfstr%20%281%29.gif)

**Comment by kshmidt-digma** [comment] 2023-09-07 19:37
Duplicate of https://github.com/digma-ai/digma-ui/issues/211

**Closed** 2023-09-07 19:37 UTC
Labels: bug, beta_user
