### ISSUE TITLE
Registration notification

### ISSUE THREAD

**Issue by doppleware** [digma-ai/digma-intellij-plugin#1671] opened 2024-01-24 22:21 UTC
If the following is true:

1. The user has been active for at least two weeks
2. The user has performed at least 20 online user action

Show the user a notification: 
Digma is free but please register!
Use this link to register your free developer account

The link should open the observability panel with the registration dialog (the same one we use for add env)

**Comment by shalom938** [comment] 2024-01-28 22:35
@kshmidt-digma 
we probably need a new message for that right?

**Comment by kshmidt-digma** [comment] 2024-01-29 09:01
@shalom938 
Yes, we would need to add a new message to open the registration dialog in the Observability panel. Something like `RECENT_ACTIVITY/OPEN_REGISTRATION_DIALOG`

**Comment by shalom938** [comment] 2024-01-29 10:21
@kshmidt-digma 
ok, can you prepare a branch and let me know?

**Comment by kshmidt-digma** [comment] 2024-01-29 12:15
@shalom938 
Sure, I created a ticket for the UI task: https://github.com/digma-ai/digma-ui/issues/393

**Comment by shalom938** [comment] 2024-03-05 20:34
closed as duplicate of
https://github.com/digma-ai/digma-intellij-plugin/issues/1895

**Closed** 2024-03-05 20:36 UTC
