### ISSUE TITLE
Runtime Exception at Intellij

### ISSUE THREAD

**Issue by arik-dig** [digma-ai/digma-intellij-plugin#449] opened 2023-03-30 10:44 UTC
### Plugin Version 
2.0.49

### Stack Trace

```
Details: Current thread: Thread[ApplicationImpl pooled thread 22,4,main] 2145677508
Dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0,6,main] 101365907

java.lang.Throwable: Read access is allowed from inside read-action (or EDT) only (see com.intellij.openapi.application.Application.runReadAction())
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:228)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:988)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:767)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:390)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:167)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:103)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:91)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:34)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.findPsiMethodByMethodCodeObjectId(JavaLanguageService.java:340)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.lambda$findWorkspaceUrisForMethodCodeObjectIds$3(JavaLanguageService.java:321)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.idea.psi.java.JavaLanguageService.findWorkspaceUrisForMethodCodeObjectIds(JavaLanguageService.java:319)
	at org.digma.intellij.plugin.insights.view.WorkspaceUrisHelper.findWorkspaceUrisMethodCodeObjectIds(WorkspaceUrisHelper.java:37)
	at org.digma.intellij.plugin.insights.view.WorkspaceUrisHelper.findWorkspaceUrisForMethodCodeObjectIds(WorkspaceUrisHelper.java:28)
	at org.digma.intellij.plugin.insights.view.GroupListViewItemBuilder.build(GroupListViewItemBuilder.java:63)
	at org.digma.intellij.plugin.insights.view.InsightsViewBuilder.lambda$build$0(InsightsViewBuilder.java:49)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.digma.intellij.plugin.insights.view.InsightsViewBuilder.build(InsightsViewBuilder.java:47)
	at org.digma.intellij.plugin.insights.InsightsProvider.getInsightsListContainer(InsightsProvider.java:58)
	at org.digma.intellij.plugin.insights.InsightsProvider.getCachedInsights(InsightsProvider.java:44)
	at org.digma.intellij.plugin.ui.service.InsightsViewService.updateInsightsModel(InsightsViewService.kt:60)
	at org.digma.intellij.plugin.service.EditorInteractionService.contextChangedImpl(EditorInteractionService.java:129)
	at org.digma.intellij.plugin.service.EditorInteractionService.lambda$contextChanged$0(EditorInteractionService.java:76)
	at org.digma.intellij.plugin.common.Backgroundable$1.run(Backgroundable.java:29)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:474)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:589)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:664)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:620)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:588)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by arik-dig** [comment] 2023-04-04 06:44
looking at intellij bug tracking
https://youtrack.jetbrains.com/issues?q=%22Read%20access%20is%20allowed%20from%20inside%20read-action%20(or%20EDT)%20only%22

this issue seems to be very common.
having said that still not sure yet how to solve it

**Comment by arik-dig** [comment] 2023-04-13 13:45
also asked a question is slack:

https://jetbrains-platform.slack.com/archives/C5U8BM1MK/p1680606547127249

**Comment by arik-dig** [comment] 2023-04-13 13:46
based on answer at slack we need to follow threading rules:

https://plugins.jetbrains.com/docs/intellij/general-threading-rules.html

**Comment by shalom938** [comment] 2023-04-14 14:23
@arik-dig I fixed that yesterday , @shaykeren asked me to fix issue [526](https://github.com/digma-ai/digma-intellij-plugin/issues/526 ) which you closed as duplicate of this one.

the call to JavaFullClassNameIndex.get must execute with read access , some flows are already covered and execute with ReadAction and some don't. 
what i did is in JavaLanguageService#findPsiMethodByMethodCodeObjectId always executes the search for the Method in a ReadAction if not already running with read access. you can see it in ReadActions#ensureReadAction(java.util.function.Supplier<T>)

I think you can close this bug too.

**Closed** 2023-04-16 10:25 UTC
Labels: bug, Runtime/IntelliJ IDEA
